<template>
  <div class="app-register-header">
      <i class="fa fa-angle-left"></i>
      <span>注册</span>
  </div>
</template>

<script>
export default {
  name: 'app-register-header'
}
</script>

<style lang="scss">
  .app-register-header{
    height:50px;
    background:rgb(0, 195, 255);
    line-height: 50px;
    text-align: center;
    i {
      float: left;
      line-height: 0.5rem;
      font-size: 18px;
      padding-left: 0.1rem;
    }
  
  }
</style>

